application: vitalvascom
domain: [vitalvas.com, www.vitalvas.com, blog.vitalvas.com]
runtime: django#blog.wsgi
require-file: requirements.txt

handlers:
- not-host: www.vitalvas.com
  code: 301
  new-url: http://www.vitalvas.com


