application: mypage
domain: [vitalvas.com, www.vitalvas.com, blog.vitalvas.com, new.vitalvas.com]
runtime: django

handlers:
- url: /static/
  static_files: /static/
- url: /static/admin/
  static_files: /srv/env/lib/python2.6/site-packages/django/contrib/admin/static/admin/
- url: /favicon.ico
  static_files: /static/favicon.ico
- url: /robots.txt
  static_files: /static/robots.txt
- host: blog.vitalvas.com
  code: 301
  new_url: http://vitalvas.com
- host: new.vitalvas.com
  code: 301
  new_url: http://vitalvas.com

require: [django, pytils, markdown2]
